name: Auto Update Owner Trade Data

on:
  schedule:
    # รันเวลา 19:00 UTC ในวัน จันทร์, อังคาร, พุธ, พฤหัส, เสาร์
    # จะตรงกับเวลาไทย 02:00 น. ในวัน อังคาร, พุธ, พฤหัส, ศุกร์, อาทิตย์
    - cron: '0 19 * * 1,2,3,4,6'
  workflow_dispatch: 

jobs:
  scrape_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install pandas requests beautifulsoup4 lxml html5lib

      - name: Run Script
        run: python owner_trade.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add data_owner_trade/*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update trade data: $(date)" && git push)
